version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    networks:
      - app-network

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: tennis-app
#    ports:
#      - "8000:8080"
#    networks:
#      - app-network
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-container:5432/mydatabase
#      SPRING_DATASOURCE_USERNAME: myuser
#      SPRING_DATASOURCE_PASSWORD: mypassword

networks:
  app-network:
    driver: bridge
