version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tennis-app
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-cvo1ceuuk2gs73bghp30-a.frankfurt-postgres.render.com:5432/tenniskz
      SPRING_DATASOURCE_USERNAME: arystanbek
      SPRING_DATASOURCE_PASSWORD: 31EgyLxhPVWfb8AgxtIDnBbUsRpklNUG
      FILE_UPLOAD_DIRECTORY: /app/uploads

networks:
  app-network:
    driver: bridge
